### ISSUE TITLE
Toggle service fails to start when loading network hwaddress

### ISSUE THREAD

**Issue by manbehindthemadness** [intelligent-agent/toggle#8]
The service seems to load without issue the first time, but after restarting the system this is returned in the logs:

Mx-WARNING **: Error loading fallback icon theme
Traceback (most recent call last):
File "/usr/local/bin/toggle", line 9, in <module>
load_entry_point('Toggle==1.3.0', 'console_scripts', 'toggle')()
File "build/bdist.linux-armv7l/egg/toggle/Toggle.py", line 283, in main
File "build/bdist.linux-armv7l/egg/toggle/Toggle.py", line 148, in __init__
File "build/bdist.linux-armv7l/egg/toggle/Settings.py", line 34, in __init__
File "build/bdist.linux-armv7l/egg/toggle/Settings.py", line 119, in setup_wifi_tab
File "build/bdist.linux-armv7l/egg/toggle/Network.py", line 180, in get_access_points
AttributeError
'function' object has no attribute 'HwAddress'

**Comment by manbehindthemadness** [comment]
I accidentally isolated the source of the problem here:
This is the result of a connection being setup within network manager, if all connections are removed, it functions without issue.

**Comment by goeland86** [comment]
This should hopefully now be fixed in the `develop` branch, @manbehindthemadness - I know it's been a long time coming...

**Comment by Wackerbarth** [comment]
Actually, the branch that you will want is `dev`. The changes to which @goeland86 referred have been incorporated in this branch. The `develop` branch is not current and will be dropped soon.

**Comment by goeland86** [comment]
... Yeah I wasn't aware that we were going to drop `develop` - can we talk about that before you do anything drastic?

**Comment by eliasbakken** [comment]
Is this issue still valid?

**Comment by eliasbakken** [comment]
This is fixed in dev.
